homeassistant: 
  announce: true
  prefix: homeassistant
global:
  manufacturer: 'YI Tecnologies'
  model: 'YI Home Camera 1080p'
mqtt:
  base_topic: yicam
  server: 'mqtt://192.168.0.100'
cameras:
  'yi-cam-01':
    mqtt_prefix: 'yicam/yi-cam-01'
    friendly_name: 'Yi Camera 01'
    ip: '192.168.0.101'
  'yi-cam-02':
    mqtt_prefix: 'yicam/yi-cam-02'
    friendly_name: 'Yi Camera 02'
    ip: '192.168.0.102'
  'yi-cam-03':
    mqtt_prefix: 'yicam/yi-cam-03'
    friendly_name: 'Yi Camera 03'
    ip: '192.168.0.102'