name: 

on:
  push:
    tags:
      - '*'

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: enricoferro/yi-hack-2-mqtt

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [10.x, 12.x, 14.x]
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run lint

    - name: install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: build the image
      run: |
        docker buildx build \
          --tag $IMAGE_NAME:latest --tag $IMAGE_NAME:$RELEASE_VERSION \
          --output=type=registry \
          --platform linux/amd64,linux/arm/v7,linux/arm64 .
